def throw_lethal_err(msg):
    print(msg)
    exit()